services:
  - type: web
    name: inventory-management
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        sync: false
